//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Good_Luck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public decimal DonorId { get; set; }
        public decimal StudentId { get; set; }
        public Nullable<decimal> KindOfContact { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual Kind_Of_Contact Kind_Of_Contact { get; set; }
        public virtual Student Student { get; set; }
    }
}
