//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Good_Luck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kind_Of_Contact
    {
        public decimal ContactId { get; set; }
        public string ContactName { get; set; }
        public Nullable<short> Priority { get; set; }
    }
}
